### ISSUE TITLE
Can't dial up numbers in sip-trip-phone

### ISSUE THREAD

**Issue by ta123q** [DoubleBastionAdmin/sip-trip-phone#2]
When sip-trip-phone window popup, i can't press on numbers to make a call also even when i tried to enter number with my keyboard i can't press on call button.

**Comment by DoubleBastionAdmin** [comment]
Have you enterd your credentials on the Settings page of SIP Trip Phone ?

If yes, what you describe usually happens because the phone is not loaded properly in the browser. First of all, make sure your microphone is properly connected to your computer. If the microphone is not properly connected or is 'captured' by a different application, the phone won't work. Secondly, try using Firefox and disable all add-blockers. The sign that you are on the right track is when you can reproduce the following steps: log in to Nextcloud in Firefox, then click on 'Sip Trip Phone's' icon, then Firefox displays the message: "Firefox prevented this site to open a pop-up window", then you click on the 'Preferences' button next to that message, then you choose the last option in the drop down list: "Show https://cloud.example.com/apps/sip_trip_phone/phone/index.html", then the pop up opens and Firefox asks you if you allow the application to access the microphone and you click 'Allow' and then you see the message 'Ready' in the upper left corner of the application. Also, when you click on any button on the dialpad, you hear a beep sound in your headphones. If any of these steps is missing, you have a problem with your browser/microphone/app settings/add-blocker, etc.

Thirdly, make sure you have set up your Asterisk server as explained in detail [here](https://www.doublebastion.com/install-asterisk/) and you have installed and configured SIP Trip Phone as explained in detail [here](https://www.doublebastion.com/install-nextcloud/#install-sip-trip-phone).

If the phone loads properly but it doesn't connect to Asterisk, you will have to connect via SSH to your remote server and run the following commands, to see debug information displayed when the phone tries to connect:

```
asterisk -rv
core set debug 7
```

**Comment by ta123q** [comment]
still having same issue microphone is allowed , it do pop up to https://cloud.example.com/apps/sip_trip_phone/phone/index.html but it never shows 'Ready' message !


https://user-images.githubusercontent.com/109732616/184842649-7a7bd7d9-16ce-45ea-8a81-627ffc097784.mp4

**Comment by DoubleBastionAdmin** [comment]
> it never shows 'Ready' message !

This means **it's not connected to Asterisk or directly to the SIP provider**, so, you won't be able to make any calls.

The behavior that you show above is normal: as long as the phone is not connected to your Asterisk server or directly to your SIP provider and you don't see the 'Ready' message, you can't call any numbers.

Please post the answer to the following 2 questions:

1. If you are using Asterisk: have you installed and configured your Asterisk server as explained [here](https://www.doublebastion.com/install-asterisk/) ? If you try to connect SIP Trip Phone directly to your SIP provider, without using Asterisk: have you followed [these instructions](https://www.doublebastion.com/install-nextcloud/#install-sip-trip-phone) ?

2. Have you entered your 'Display Name', 'SIP User', 'SIP User Password', 'WSS URL', and 'SIP Realm' on the Settings page of SIP Trip Phone after you installed it ? To see the Settings page of the application, in Nextcloud, click on the profile picture > Settings > under Personal, click on SIP Trip Phone.

**Comment by ta123q** [comment]
Actually trying to connect it using freePBX which is connect to Asterisk as well, is it possible!

**Comment by DoubleBastionAdmin** [comment]
SIP Trip Phone has never been tested with FreePBX, so, it probably won't work. FreePBX is an additional software layer which is supposed to make interacting with Asterisk easier, but in our documentation we don't recommend using FreePBX, since configuring Asterisk directly is so easy if you know precisely what files to change. All Asterisk configuration files are located in one single folder `/etc/asterisk` and there are just a few files that have to be modified. We explain this in detail in our [guide](https://www.doublebastion.com/install-asterisk/).

An easier alternative is to connect SIP Trip Phone directly to the SIP provider, but only a few providers allow such connections, and these direct connections don't benefit from the flexibility that Asterisk brings: configuring as many extensions as you like and having gratis calls between them, call queues, IVR, number blacklisting, etc. If you have a Telnyx account, you can connect SIP Trip Phone directly to it, as we explain [here](https://www.doublebastion.com/install-nextcloud/#connect-sip-trip-phone-directly-to-telnyx). We'll be testing direct connections to Twilio and Flowroute shortly and if they work, we'll update the documentation, but Telnyx is cheaper than Twilio and Flowroute.

**Comment by ta123q** [comment]
solved issue with Asterisk, thank you.
